function getPessoas(){
    var pessoas = {};

    pessoas.sexos = [
        'Homem',
        'Mulher',
        'Ambígua, oculta'
    ];

    pessoas.nomes = [
        'Adric',
        'Aldo',
        'Amosen',
        'Andrel',
        'Arden',
        'Arlyn',
        'Arquo',
        'Arvus',
        'Ashlyn',
        'Branon',
        'Brace',
        'Brance',
        'Brena',
        'Bricks',
        'Candra',
        'Carissa',
        'Carro',
        'Casslyn',
        'Cavelle',
        'Clave',
        'Corille',
        'Cross',
        'Crowl',
        'Cyrene',
        'Daphnia',
        'Drav',
        'Edlun',
        'Emeline',
        'Grine',
        'Helles',
        'Hix',
        'Holtz',
        'Kamelin',
        'Kelyr',
        'Kobb',
        'Kristov',
        'Laudius',
        'Lauria',
        'Lenia',
        'Lizete',
        'Lorette',
        'Lucella',
        'Lynthia',
        'Mara',
        'Milos',
        'Morlan',
        'Myre',
        'Narcus',
        'Naria',
        'Noggs',
        'Odrienne',
        'Orlan',
        'Phin',
        'Polonia',
        'Quess',
        'Remira',
        'Ring',
        'Roethe',
        'Sesereth',
        'Sethla',
        'Skannon',
        'Stavrul',
        'Stev',
        'Syra',
        'Talitha',
        'Tesslyn',
        'Tena',
        'Timoth',
        'Tocker',
        'Una',
        'Vaurin',
        'Veleris',
        'Veretta',
        'Vestine',
        'Vey',
        'Volette',
        'Vond',
        'Weaver',
        'Wester',
        'Zamira',
    ];

    pessoas.sobrenomes = [
        'Ankhayat',
        'Arcolongo',
        'Arran',
        'Athanoch',
        'Basran',
        'Boden',
        'Booker',
        'Brogan',
        'Clelland',
        'Coleburn',
        'Comber',
        'Daava',
        'Dalmore',
        'Danfeld',
        'Dunvil',
        'Farros',
        'Grine',
        'Haig',
        'Helker',
        'Helles',
        'Hellyers',
        'Jayan',
        'Jeduin',
        'Kardera',
        'Karstas',
        'Keel',
        'Kessarin',
        'Kinclaith',
        'Lomond',
        'Maroden',
        'Michter',
        'Monteclaro',
        'Morriston',
        'Penderyn',
        'Prichard',
        'Rompeferro',
        'Rowan',
        'Sevoy',
        'Skelkallan',
        'Skora',
        'Slane',
        'Vaustranho',
        'Vieira',
        'Vilasacra',
        'Tyrconnell',
        'Vale',
        'Walund',
        'Welker',
    ];

    pessoas.alcunhas = [
        'Agulha',
        'Alecrim',
        'Artilheiro',
        'Badalada',
        'Besouro',
        'Carvalho',
        'Chicote',
        'Corvo',
        'Cruz',
        'Dados',
        'Dúzias',
        'Eco',
        'Esfolador',
        'Espinho',
        'Espora',
        'Gancho',
        'Garra',
        'Gelo',
        'Grilo',
        'Lua',
        'Martelo',
        'Melodia',
        'Mola',
        'Névoa',
        'Ogro',
        'Palestra',
        'Parça',
        'Pedrada',
        'Prata',
        'Prego',
        'Pulga',
        'Raposa',
        'Rosa',
        'Rubi',
        'Sapo',
        'Sino',
        'Sinuca',
        'Sucateiro',
        'Tic-tac',
        'Tijolo',
        'Vime',
    ];

    pessoas.aparencias = [
        'Grande',
        'Deslumbrante',
        'Marcada pelo tempo',
        'Esculpida',
        'Bonita',
        'Atlética',
        'Esbelta',
        'Escura',
        'Pálida',
        'Robusta',
        'Delicada',
        'Cicatrizes',
        'Ossuda',
        'Desgastada',
        'Grosseira',
        'Gorda',
        'Esguia',
        'Marcante',
        'Pequena',
        'Alta',
        'Sexy',
        'Selvagem',
        'Elegante',
        'Curvada',
        'Simpática',
        'Simples',
        'Velha',
        'Jovem',
        'Estilosa',
        'Estranha',
        'Desfigurada, Mutilada',
        'Óculos, Monóculo',
        'Prótese, Aleijada',
        'Cabelo Longo, Barba, Peruca',
        'Cabelo Raspado, Careca',
        'Tatuada',
    ];

    pessoas.objetivos = [
        'Riqueza',
        'Poder',
        'Autoridade',
        'Fama, Prestígio',
        'Controle',
        'Conhecimento',
        'Prazer',
        'Vingança',
        'Liberdade',
        'Auto Realização',
        'Felicidade',
        'Medo, Infâmia',
        'Respeito',
        'Amor',
        'Mudança',
        'Caos, Destruição',
        'Justiça',
        'Cooperação',
    ];

    pessoas.metodos = [
        'Violência',
        'Ameaças',
        'Negociação',
        'Estudo',
        'Manipulação',
        'Estratégia',
        'Roubo',
        'Arcano',
        'Comércio',
        'Trabalho Duro',
        'Lei, Política',
        'Sabotagem',
        'Subterfúgio',
        'Alquimia',
        'Chantagem',
        'Trabalho em Equipe',
        'Espionagem',
        'Caos',
    ];

    pessoas.profissoes = {};

    pessoas.profissoes.comum = [
        'Padeiro',
        'Barbeiro',
        'Ferreiro',
        'Cervejeiro',
        'Açougueiro',
        'Carpinteiro',
        'Carroceiro',
        'Merceeiro',
        'Escrivão',
        'Sapateiro',
        'Toneleiro',
        'Cultivador',
        'Condutor',
        'Tintureiro',
        'Bordador',
        'Vendedor de Peixe',
        'Gondoleiro',
        'Guarda',
        'Artesão de Couro',
        'Pedreiro',
        'Mercador',
        'Telhador',
        'Cordoeiro',
        'Tapeteiro',
        'Servo',
        'Construtor Naval',
        'Criminoso',
        'Alfaiate',
        'Curtidor de Couro',
        'Funileiro',
        'Vendedor',
        'Tecelão',
        'Marceneiro',
        'Pastor de Cabras',
        'Mensageiro',
        'Marujo',
    ];

    pessoas.profissoes.rara = [
        'Advogado',
        'Arquiteto',
        'Artista',
        'Autor',
        'Oficial de Justiça',
        'Apiário',
        'Banqueiro',
        'Caçador de Recompensas',
        'Relojoeiro',
        'Cortesão',
        'Vendedor de Peles',
        'Vidraceiro',
        'Diplomata',
        'Carcereiro',
        'Joalheiro',
        'Doutor',
        'Chaveiro',
        'Juiz',
        'Musicista',
        'Médico',
        'Encanador',
        'Tipógrafo',
        'Estudioso',
        'Escriba',
        'Faisqueiro (Garimpeiro)',
        'Coletor de Impostos',
        'Tesoureiro',
        'Sussurro',
        'Compositor',
        'Camareiro',
        'Capitão',
        'Patrulheiro Espiritual',
        'Jornalista',
        'Explorador',
        'Peão dos Trilhos',
        'Soldado',
    ];

    pessoas.tracos = [
        'Carismático',
        'Frio',
        'Cavalheiresco',
        'Ousado',
        'Desconfiado',
        'Obsessivo',
        'Astuto',
        'Quieto',
        'Temperamental',
        'Feroz',
        'Descuidado',
        'Sigiloso',
        'Impiedoso',
        'Calculista',
        'Desafiante',
        'Cortês',
        'Perspicaz',
        'Desonesto',
        'Paciente',
        'Cruel',
        'Sofisticado',
        'Paranóico',
        'Entusiasmado',
        'Elitista',
        'Violento',
        'Cooperativo',
        'Arrogante',
        'Confiante',
        'Vaidoso',
        'Audacioso',
        'Volátil',
        'Sincero',
        'Sutil',
        'Melancólico',
        'Enigmático',
        'Calmo',
    ];

    pessoas.interesses = [
        'Uísque, vinho ou cerveja de qualidade',
        'Comida, restaurantesde qualidade',
        'Roupas, joias, peles de qualidade',
        'Belas artes, ópera, teatro',
        'Desenhos, pinturas, esculturas',
        'História, lendas',
        'Arquitetura, decoração',
        'Poesia, novelas, escrita',
        'Lutas de arena, duelos',
        'Deuses esquecidos',
        'Igreja do Êxtase',
        'Via dos Ecos',
        'Dama Lacrimosa, caridade',
        'Antiguidades, artefatos e lembrancinhas',
        'Cavalos, montaria',
        'Engenhocas, novas tecnologias',
        'Colecionador de armas',
        'Música, instrumentos, dança',
        'Caçada, pontaria',
        'Culinária, jardinagem',
        'Jogatina, cartas, dados',
        'Filosofia natural',
        'Drogas, essências, tabaco',
        'Amantes, romances, casos',
        'Festas, eventos sociais',
        'Exploração, aventura',
        'Animais de estimação (cães, gatos, pássaros)',
        'Ofício (trabalho c/ couro, etc)',
        'Navios, navegação',
        'Política, jornalismo',
        'Livros, rituais arcanos',
        'Espectrologia, electroplasma',
        'Alquimia, medicina',
        'Essências, alquimia',
        'Lendas, conhecimento demoníaco',
        'Lendas anteriores ao cataclisma',
    ];

    pessoas.peculiaridades = [
        'Supersticioso. Acredita em sinais, números mágicos',
        'Dedicado a sua família',
        'Casou-se com uma família importante/poderosa',
        'Mantém sua posição para espionar para outra facção',
        'Recluso. Prefere interagir através de mensageiros',
        'Débitos enormes (a bancos/criminosos/família)',
        'Não nota os defeitos de amigos, aliados, familiares',
        'Já foi um vazio, mas foi restaurado. Imune a espíritos',
        'Sofre de doença crônica e requer cuidados constantes',
        'Controlado secretamente (abertamente?) por um espírito possuidor',
        'Serve aos interesses de um demônio (ciente ou não)',
        'Orgulho de suas raízes, tradições, idioma natal',
        'Preocupado com as aparências, fofocas e colegas',
        'Frequentemente prejudicado pelo seu vício em drogas/álcool',
        'Mantém a sua posição através de chantagem',
        'Depende de conselhos para tomar decisões',
        'Envolvido em crimes de guerra na Guerra da União',
        'Mantém uma vida dupla usando outra identidade',
        'Ovelha negra/exilado de família ou organização',
        'Prisioneiro ou em prisão domiciliar',
        'Muito viajado. Contatos fora de Doskvol',
        'Revolucionário. Trama contra o Imperium',
        'Herdou a sua posição. Não necessariamente a merece ou deseja',
        'Celebridade. Popularizado em prosa/canções/teatro',
        'Reputação escandalosa (merecida ou não)',
        'Cercado de puxa-sacos, suplicantes, seguidores',
        'Reputação imaculada. Altamente respeitado',
        'Preconceito contra cultura/crença/classe social',
        'Visionário. Tem visões radicais para o futuro',
        'Amaldiçoado, assombrado, importunado por espíritos ou demônio',
        'Fobia ou desprezo intenso e irracional',
        'Educação extensa em todos os assuntos acadêmicos',
        'Mantém diários, notas, registros, álbuns, detalhados',
        'Cegamente leal a um ideal, grupo ou tradição',
        'Muito tradicional. Se opõe a novas ideias',
        'Uma fraude. Algum aspecto importante é falsificado',
    ];

    return pessoas;
}