function getPredios(){
    var predios = {};

    predios.exterior = {};

    predios.exterior.materiais = [
        'Tijolo Cinza',
        'Pedras e Madeira',
        'Blocos de Pedra',
        'Placas de Madeira',
        'Gesso e Madeira',
        'Folhas de Metal',
    ];  

    predios.exterior.detalhes = [
        'Azulejos',
        'Decoração em Metal',
        'Decoração em Vidro',
        'Decoração em Pedra',
        'Decoração em Madeira',
        'Jardins Ornamentais',
    ];

    predios.ocupacao = {};

    predios.ocupacao.comum = [
        'Albergue',
        'Estalagem',
        'Taverna',
        'Casa de Jogos',
        'Boca de Fumo',
        'Bordel',
        'Mercado',
        'Oficina',
        'Padaria',
        'Açougue',
        'Forja',
        'Costureiro',
        'Albergue de Trabalho',
        'Estábulos de Cabras',
        'Cervejaria',
        'Posto de Guarda',
        'Corte de Justiça, Prisão',
        'Doca',
        'Ruína',
        'Casas Geminadas (Gêmeas)',
        'Cortiço',
        'Apartamentos',
        'Casa Pequena',
        'Casa de Banho',
        'Santuário',
        'Tatuador',
        'Médico',
        'Arena de Luta',
        'Praça, Fonte',
        'Gruta',
        'Armazém',
        'Curral',
        'Fábrica',
        'Refinaria',
        'Enguiaria',
        'Jardim de Cogumelos',
    ];

    predios.ocupacao.rara = [
        'Mercado de Fazendeiros',
        'Restaurante',
        'Bar de Luxo',
        'Academia',
        'Salão de Beleza',
        'Café',
        'Florista',
        'Vendedor de Tabaco',
        'Livraria',
        'Joalheiro',
        'Alfaiate',
        'Galeria',
        'Apotecário',
        'Estábulos de Cavalo',
        'Destilaria',
        'Loja de Vinhos',
        'Mestre Artesão',
        'Casa de Barcos',
        'Teatro',
        'Casa de Ópera',
        'Apartamentos',
        'Sobrado',
        'Vila',
        'Clínica',
        'Templo',
        'Cisterna (Caixa D\'agua)',
        'Posto da Guarda',
        'Parque',
        'Monumento',
        'Arquivo',
        'Espiritualista',
        'Banco',
        'Alquimista',
        'Usina de Energia',
        'Jardim de Energia Radiante',
    ];

    predios.detalhes = [
        'Gotejarde Água',
        'Rangido do Assoalho',
        'Crepitar de Fogueiras',
        'Fumaça de Lâmpadas',
        'Zunido de Luzes Elétricas',
        'Tique-Taque de Mecanismos',
        'Plantas, Flores',
        'Tapeçarias, Quadros',
        'Persianas nas Janelas',
        'Cortinas Pesadas,  ',
        'Tapetes Grossos',
        'Poeira, Detritos',
        'Muito Uso, Danificado',
        'Puídas, Esfarrapadas',
        'Móveis Utilitários',
        'Adornos Elegantes',
        'Confortável, Exuberante',
        'Simplicidade Caseira',
        'Austeridade Espartana (Rígido, sevéro, de caráter inabalável)',
        'Escadas Circulares',
        'Portas Secretas',
        'Passarelas',
        'Claraboias',
        'Sacada',
        'Adega',
        'Ventilado, Frio',
        'Quieto, Robusto',
        'Cálido, Aconchegante',
        'Alto, Espaçoso',
        'Baixo, Apertado',
        'Frágil, Decrépito',
        'Dispositivos Estranhos',
        'Artefatos Esquisitos',
        'Proteções, Runas Antigas',
        'Pilha de Curiosidades',
        'Móveis Antiquados',
        'Santuário, Altar',
    ];

    return predios;

}
